sudo: required

language: node_js

node_js:
  - "10.4.1"

before_install:
  - npm i -g npm@version-number
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - "node_modules"
    - "/opt/blender"

services:
  - docker
