sudo: required

language: node_js

node_js:
  - "10.4.1"

before_install:
  - npm i -g npm@6.1.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - docker exec -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH"

cache:
  yarn: true
  directories:
    - "node_modules"
    - ".bin"

services:
  - docker

before_script:
  - yarn setup
