version: "2"
services:
  apis:
    restart: "no"
    command: yarn local:test
    environment:
      - TRAVIS_JOB_NUMBER
      - TRAVIS_BUILD_NUMBER
      - TRAVIS_PYTHON_VERSION
      - TRAVIS
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - TRAVIS_PULL_REQUEST
