version: "2"
services:
  apis:
    container_name: apis
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    command: yarn prod:start
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
